apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "etherpad.fullname" . }}
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config_variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
