apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "etherpad.fullname" . }}
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
data:
  TITLE: "{{.Values.etherpad.TITLE }}"
  SKIN_NAME: "{{.Values.etherpad.SKIN_NAME }}"
  DEFAULT_PAD_TEXT: "{{.Values.etherpad.DEFAULT_PAD_TEXT }}"
  TRUST_PROXY: "{{.Values.etherpad.TRUST_PROXY }}"
  REQUIRE_AUTHENTICATION: "{{.Values.etherpad.REQUIRE_AUTHENTICATION }}"
  REQUIRE_AUTHORIZATION: "{{.Values.etherpad.REQUIRE_AUTHORIZATION }}"
  REQUIRE_SESSION: "{{.Values.etherpad.REQUIRE_SESSION }}"
