apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etherpad.fullname" . }}
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "etherpad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "etherpad.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etherpad.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "etherpad.fullname" . }}
          env:
            - name: DB_TYPE
              value: postgrespool
            - name: DB_HOST
              value: {{ template "etherpad.db.fullname" . }}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
            - name: DB_USER
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: etherpad-secret
                  key: postgresql-password
            {{- if .Values.adminPass }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etherpad-secret
                  key: admin-password
            {{- end }}
            {{- if .Values.userPass }}
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etherpad-secret
                  key: user-password
            {{- end }}
          ports:
            - name: http
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ default "/" .Values.livenessPath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ default "/" .Values.readinessPath }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
