{{ if not (default false .Values.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "etherpad-secret" .Values.secretName }}
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.addDbPass }}
  postgresql-password: {{ include "dbPass" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.addAdminPass }}
  admin-password: {{ include "adminPass" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.addUserPass }}
  user-password: {{ include "userPass" . | b64enc | quote }}
  {{- end }}
{{- end }}
