{{- if (or .Values.postgresql.postgresqlPassword .Values.adminPass .Values.userPass) and (default true .Values.create_secret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: etherpad-secret
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.postgresqlPassword }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  {{- end }}
  {{- if .Values.adminPass }}
  admin-password: {{ .Values.adminPass | b64enc }}
  {{- end }}
  {{- if .Values.userPass }}
  user-password: {{ .Values.userPass | b64enc }}
  {{- end }}
{{- end }}
