{{- if or .Values.postgresql.postgresqlPassword .Values.admin_pass .Values.user_pass }}
apiVersion: v1
kind: Secret
metadata:
  name: etherpad-secret
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.postgresqlPassword }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  {{- end }}
  {{- if .Values.admin_pass }}
  admin-password: {{ .Values.admin_pass | b64enc }}
  {{- end }}
  {{- if .Values.user_pass }}
  user-password: {{ .Values.user_pass | b64enc }}
  {{- end }}
{{- end }}
